[package]
name = "hal9000-derive"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@elizas.website>"]

[lib]
proc-macro = true

[dependencies.syn]
version = "0.14"
features = ["full", "extra-traits"]

[dependencies]
quote = "0.6.8"
proc-macro2 = "0.4"
